const PetsData = [
    {
        id: 1,
        name: "Madhav",
        image: url("../../public/images/step.jpg"),
        category: "Dog",
        gender: "male",
        age: "10 months",
        location: "CGC",
        description: "This is madhav(street dog).",
        fwc: "Yes",
        breed: "Street Dog",
        contact: "+91-9142102268",
        email: "pratik2015.kumar@gmail.com",
    },
    {
        id: 2,
        name: "Manibhushan",
        image: url("../../public/images/step.jpg"),
        category: "Cat",
        gender: "female",
        age: "10 months",
        location: "CGC",
        description: "This is manibhushan(street cat).",
        fwc: "Yes",
        breed: "Street Cat",
        contact: "+91-9142102268",
        email: "pratik2015.kumar@gmail.com",
    },
    {
        id: 3,
        name: "Kamdhenu",
        image: url("../../public/images/step.jpg"),
        category: "Cow",
        gender: "female",
        age: "10 months",
        location: "CGC",
        description: "This is Kamdhenu.",
        fwc: "Yes",
        breed: "Cow",
        contact: "+91-9142102268",
        email: "pratik2015.kumar@gmail.com",
    }
]

export default PetsData;